version: "3.7"
services:
  trino:
      build: .
      image: trino-rafael:1
      hostname: my-localhost-trino
      user: root
      container_name: my-localhost-trino
      networks:
        - trino-demo
      ports:
        - 8087:8080
        - 8443:8443
networks:
  trino-demo:
    driver: bridge
